### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by larsbrinkhoff** [stefanberndtsson/ostis#26]
The `tests` subdirectory doesn't do much.

I propose to add automated tests which takes disk images, and verifies that they run correctly.

To do that, we'd need to able to inspect what is happening inside the emulator.  I see that `cpu.h` has a debugging API which can be used for that.

We would also have to inject input from devices, e.g. key presses and mouse movement.  `ikbd.c` already has functions for that.

Finally, to automate the tests, we'd probably have to disable SDL output.

When all this is in place, every commit can be automatically built and tested in a CI service like Travis CI.

**Comment by stefanberndtsson** [comment]
Yep, I want to rip up the current test stuff. It's useless for now.

I would like highly specialised bootsector code (preferably not larger for tests, but might be, in which case it'll have to be handled somehow). Bootsector stuff runs early, but still keeps the full basic system setup. This wouldn't require a full disk image, as long as the image loader can handle it.

In the 68010 (which is not emulated anyway) there are 8 instructions (BKPT) $4848-$484F that could be used for signaling things to the test environment.

For example, $4848 could be a signal to reset all hw-counters and cpu cycles and such to a known value, then run code until $484F which exits the test. The state of cpu/mfp/memory could then be compared to expected values. On the other hand, the point at which a bootsector is started should be possible to keep to a known state anyway, so the resetting might not be needed.

Other BKPT:s could be used to signal the test case for input injections or force debug outputs.

The entire system should be running with all hardware, but, as you say, no actual output produced. This should be fairly simple since the pixel output is done to a pixels array, that can be any memory area. So the screen output can then also be compared to known states.

The current cpu debugging interface wouldn't really make much sense then, since the test case can access all the data anyway though normal function calls. Hence, I'd prefer to rip that up as well.

This whole thing would probably need a BKPT-function that the test code inserts into the instr[] array, and a separate cpu_run() that can exit back to the test code. The test build would then essentially be a full build which runs test_init() and test_cpu_run() instead of cpu_run(), and that's mostly it.

It needs to somehow load its testcase (maybe all of them are compiled in, maybe the tests are multiple compilations, I don't know), and its disk image.

**Comment by larsbrinkhoff** [comment]
I'm thinking about running real applications (aka demos, games) from unmodified disk images.  But we can have both!

For each such test, there would be some work to investigate how the program works, and how to detect a success/failure. Once that is done, the test can written to set breakpoints with `cpu_set_breakpoint` and investigate the state there.  Or, given that the simulation runs deterministically, just wait a number of cycles.

**Comment by larsbrinkhoff** [comment]
I suppose some tests can be done without a disk image, if you put them in a special ROM image.

**Comment by stefanberndtsson** [comment]
True, or a cartridge (which is checked for in the third instruction of the ROM), if you want to keep the TOS-ROM in place. Should be easy to implement cartridge support. All that's needed is $FA52235F as first LONG, then your code after that.

**Comment by stefanberndtsson** [comment]
I pushed a testing concept to master now, that uses the cartridge solution (although it should be able to load floppy images as well). Some documentation of the currenly only case is in the README.

**Comment by stefanberndtsson** [comment]
Test method seems to work for me at the moment. Closing this now.
